//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewUmass.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.ApiSoap")]
    public interface ApiSoap {
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 bytes 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UploadLicense", ReplyAction="*")]
        NewUmass.ServiceReference1.UploadLicenseResponse UploadLicense(NewUmass.ServiceReference1.UploadLicenseRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UploadLicense", ReplyAction="*")]
        System.Threading.Tasks.Task<NewUmass.ServiceReference1.UploadLicenseResponse> UploadLicenseAsync(NewUmass.ServiceReference1.UploadLicenseRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 bytes 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UploadInfoImg", ReplyAction="*")]
        NewUmass.ServiceReference1.UploadInfoImgResponse UploadInfoImg(NewUmass.ServiceReference1.UploadInfoImgRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UploadInfoImg", ReplyAction="*")]
        System.Threading.Tasks.Task<NewUmass.ServiceReference1.UploadInfoImgResponse> UploadInfoImgAsync(NewUmass.ServiceReference1.UploadInfoImgRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 domain 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCompanyId", ReplyAction="*")]
        NewUmass.ServiceReference1.GetCompanyIdResponse GetCompanyId(NewUmass.ServiceReference1.GetCompanyIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCompanyId", ReplyAction="*")]
        System.Threading.Tasks.Task<NewUmass.ServiceReference1.GetCompanyIdResponse> GetCompanyIdAsync(NewUmass.ServiceReference1.GetCompanyIdRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 json 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateKeywordRanking", ReplyAction="*")]
        NewUmass.ServiceReference1.UpdateKeywordRankingResponse UpdateKeywordRanking(NewUmass.ServiceReference1.UpdateKeywordRankingRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateKeywordRanking", ReplyAction="*")]
        System.Threading.Tasks.Task<NewUmass.ServiceReference1.UpdateKeywordRankingResponse> UpdateKeywordRankingAsync(NewUmass.ServiceReference1.UpdateKeywordRankingRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 GetLoginUrlResult 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetLoginUrl", ReplyAction="*")]
        NewUmass.ServiceReference1.GetLoginUrlResponse GetLoginUrl(NewUmass.ServiceReference1.GetLoginUrlRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetLoginUrl", ReplyAction="*")]
        System.Threading.Tasks.Task<NewUmass.ServiceReference1.GetLoginUrlResponse> GetLoginUrlAsync(NewUmass.ServiceReference1.GetLoginUrlRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 PushInfoResult 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PushInfo", ReplyAction="*")]
        NewUmass.ServiceReference1.PushInfoResponse PushInfo(NewUmass.ServiceReference1.PushInfoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PushInfo", ReplyAction="*")]
        System.Threading.Tasks.Task<NewUmass.ServiceReference1.PushInfoResponse> PushInfoAsync(NewUmass.ServiceReference1.PushInfoRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UploadLicenseRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UploadLicense", Namespace="http://tempuri.org/", Order=0)]
        public NewUmass.ServiceReference1.UploadLicenseRequestBody Body;
        
        public UploadLicenseRequest() {
        }
        
        public UploadLicenseRequest(NewUmass.ServiceReference1.UploadLicenseRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UploadLicenseRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public byte[] bytes;
        
        public UploadLicenseRequestBody() {
        }
        
        public UploadLicenseRequestBody(int id, byte[] bytes) {
            this.id = id;
            this.bytes = bytes;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UploadLicenseResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UploadLicenseResponse", Namespace="http://tempuri.org/", Order=0)]
        public NewUmass.ServiceReference1.UploadLicenseResponseBody Body;
        
        public UploadLicenseResponse() {
        }
        
        public UploadLicenseResponse(NewUmass.ServiceReference1.UploadLicenseResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UploadLicenseResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string UploadLicenseResult;
        
        public UploadLicenseResponseBody() {
        }
        
        public UploadLicenseResponseBody(string UploadLicenseResult) {
            this.UploadLicenseResult = UploadLicenseResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UploadInfoImgRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UploadInfoImg", Namespace="http://tempuri.org/", Order=0)]
        public NewUmass.ServiceReference1.UploadInfoImgRequestBody Body;
        
        public UploadInfoImgRequest() {
        }
        
        public UploadInfoImgRequest(NewUmass.ServiceReference1.UploadInfoImgRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UploadInfoImgRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public byte[] bytes;
        
        public UploadInfoImgRequestBody() {
        }
        
        public UploadInfoImgRequestBody(int id, byte[] bytes) {
            this.id = id;
            this.bytes = bytes;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UploadInfoImgResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UploadInfoImgResponse", Namespace="http://tempuri.org/", Order=0)]
        public NewUmass.ServiceReference1.UploadInfoImgResponseBody Body;
        
        public UploadInfoImgResponse() {
        }
        
        public UploadInfoImgResponse(NewUmass.ServiceReference1.UploadInfoImgResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UploadInfoImgResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string UploadInfoImgResult;
        
        public UploadInfoImgResponseBody() {
        }
        
        public UploadInfoImgResponseBody(string UploadInfoImgResult) {
            this.UploadInfoImgResult = UploadInfoImgResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCompanyIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCompanyId", Namespace="http://tempuri.org/", Order=0)]
        public NewUmass.ServiceReference1.GetCompanyIdRequestBody Body;
        
        public GetCompanyIdRequest() {
        }
        
        public GetCompanyIdRequest(NewUmass.ServiceReference1.GetCompanyIdRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetCompanyIdRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string domain;
        
        public GetCompanyIdRequestBody() {
        }
        
        public GetCompanyIdRequestBody(string domain) {
            this.domain = domain;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCompanyIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCompanyIdResponse", Namespace="http://tempuri.org/", Order=0)]
        public NewUmass.ServiceReference1.GetCompanyIdResponseBody Body;
        
        public GetCompanyIdResponse() {
        }
        
        public GetCompanyIdResponse(NewUmass.ServiceReference1.GetCompanyIdResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetCompanyIdResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int GetCompanyIdResult;
        
        public GetCompanyIdResponseBody() {
        }
        
        public GetCompanyIdResponseBody(int GetCompanyIdResult) {
            this.GetCompanyIdResult = GetCompanyIdResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateKeywordRankingRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateKeywordRanking", Namespace="http://tempuri.org/", Order=0)]
        public NewUmass.ServiceReference1.UpdateKeywordRankingRequestBody Body;
        
        public UpdateKeywordRankingRequest() {
        }
        
        public UpdateKeywordRankingRequest(NewUmass.ServiceReference1.UpdateKeywordRankingRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateKeywordRankingRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int companyId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int typeId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string json;
        
        public UpdateKeywordRankingRequestBody() {
        }
        
        public UpdateKeywordRankingRequestBody(int companyId, int typeId, string json) {
            this.companyId = companyId;
            this.typeId = typeId;
            this.json = json;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateKeywordRankingResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateKeywordRankingResponse", Namespace="http://tempuri.org/", Order=0)]
        public NewUmass.ServiceReference1.UpdateKeywordRankingResponseBody Body;
        
        public UpdateKeywordRankingResponse() {
        }
        
        public UpdateKeywordRankingResponse(NewUmass.ServiceReference1.UpdateKeywordRankingResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateKeywordRankingResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool UpdateKeywordRankingResult;
        
        public UpdateKeywordRankingResponseBody() {
        }
        
        public UpdateKeywordRankingResponseBody(bool UpdateKeywordRankingResult) {
            this.UpdateKeywordRankingResult = UpdateKeywordRankingResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetLoginUrlRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetLoginUrl", Namespace="http://tempuri.org/", Order=0)]
        public NewUmass.ServiceReference1.GetLoginUrlRequestBody Body;
        
        public GetLoginUrlRequest() {
        }
        
        public GetLoginUrlRequest(NewUmass.ServiceReference1.GetLoginUrlRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetLoginUrlRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int companyId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int b2bId;
        
        public GetLoginUrlRequestBody() {
        }
        
        public GetLoginUrlRequestBody(int companyId, int b2bId) {
            this.companyId = companyId;
            this.b2bId = b2bId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetLoginUrlResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetLoginUrlResponse", Namespace="http://tempuri.org/", Order=0)]
        public NewUmass.ServiceReference1.GetLoginUrlResponseBody Body;
        
        public GetLoginUrlResponse() {
        }
        
        public GetLoginUrlResponse(NewUmass.ServiceReference1.GetLoginUrlResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetLoginUrlResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetLoginUrlResult;
        
        public GetLoginUrlResponseBody() {
        }
        
        public GetLoginUrlResponseBody(string GetLoginUrlResult) {
            this.GetLoginUrlResult = GetLoginUrlResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PushInfoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PushInfo", Namespace="http://tempuri.org/", Order=0)]
        public NewUmass.ServiceReference1.PushInfoRequestBody Body;
        
        public PushInfoRequest() {
        }
        
        public PushInfoRequest(NewUmass.ServiceReference1.PushInfoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class PushInfoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int infoId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int b2bId;
        
        public PushInfoRequestBody() {
        }
        
        public PushInfoRequestBody(int infoId, int b2bId) {
            this.infoId = infoId;
            this.b2bId = b2bId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PushInfoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PushInfoResponse", Namespace="http://tempuri.org/", Order=0)]
        public NewUmass.ServiceReference1.PushInfoResponseBody Body;
        
        public PushInfoResponse() {
        }
        
        public PushInfoResponse(NewUmass.ServiceReference1.PushInfoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class PushInfoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string PushInfoResult;
        
        public PushInfoResponseBody() {
        }
        
        public PushInfoResponseBody(string PushInfoResult) {
            this.PushInfoResult = PushInfoResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ApiSoapChannel : NewUmass.ServiceReference1.ApiSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ApiSoapClient : System.ServiceModel.ClientBase<NewUmass.ServiceReference1.ApiSoap>, NewUmass.ServiceReference1.ApiSoap {
        
        public ApiSoapClient() {
        }
        
        public ApiSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ApiSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ApiSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ApiSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NewUmass.ServiceReference1.UploadLicenseResponse NewUmass.ServiceReference1.ApiSoap.UploadLicense(NewUmass.ServiceReference1.UploadLicenseRequest request) {
            return base.Channel.UploadLicense(request);
        }
        
        public string UploadLicense(int id, byte[] bytes) {
            NewUmass.ServiceReference1.UploadLicenseRequest inValue = new NewUmass.ServiceReference1.UploadLicenseRequest();
            inValue.Body = new NewUmass.ServiceReference1.UploadLicenseRequestBody();
            inValue.Body.id = id;
            inValue.Body.bytes = bytes;
            NewUmass.ServiceReference1.UploadLicenseResponse retVal = ((NewUmass.ServiceReference1.ApiSoap)(this)).UploadLicense(inValue);
            return retVal.Body.UploadLicenseResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NewUmass.ServiceReference1.UploadLicenseResponse> NewUmass.ServiceReference1.ApiSoap.UploadLicenseAsync(NewUmass.ServiceReference1.UploadLicenseRequest request) {
            return base.Channel.UploadLicenseAsync(request);
        }
        
        public System.Threading.Tasks.Task<NewUmass.ServiceReference1.UploadLicenseResponse> UploadLicenseAsync(int id, byte[] bytes) {
            NewUmass.ServiceReference1.UploadLicenseRequest inValue = new NewUmass.ServiceReference1.UploadLicenseRequest();
            inValue.Body = new NewUmass.ServiceReference1.UploadLicenseRequestBody();
            inValue.Body.id = id;
            inValue.Body.bytes = bytes;
            return ((NewUmass.ServiceReference1.ApiSoap)(this)).UploadLicenseAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NewUmass.ServiceReference1.UploadInfoImgResponse NewUmass.ServiceReference1.ApiSoap.UploadInfoImg(NewUmass.ServiceReference1.UploadInfoImgRequest request) {
            return base.Channel.UploadInfoImg(request);
        }
        
        public string UploadInfoImg(int id, byte[] bytes) {
            NewUmass.ServiceReference1.UploadInfoImgRequest inValue = new NewUmass.ServiceReference1.UploadInfoImgRequest();
            inValue.Body = new NewUmass.ServiceReference1.UploadInfoImgRequestBody();
            inValue.Body.id = id;
            inValue.Body.bytes = bytes;
            NewUmass.ServiceReference1.UploadInfoImgResponse retVal = ((NewUmass.ServiceReference1.ApiSoap)(this)).UploadInfoImg(inValue);
            return retVal.Body.UploadInfoImgResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NewUmass.ServiceReference1.UploadInfoImgResponse> NewUmass.ServiceReference1.ApiSoap.UploadInfoImgAsync(NewUmass.ServiceReference1.UploadInfoImgRequest request) {
            return base.Channel.UploadInfoImgAsync(request);
        }
        
        public System.Threading.Tasks.Task<NewUmass.ServiceReference1.UploadInfoImgResponse> UploadInfoImgAsync(int id, byte[] bytes) {
            NewUmass.ServiceReference1.UploadInfoImgRequest inValue = new NewUmass.ServiceReference1.UploadInfoImgRequest();
            inValue.Body = new NewUmass.ServiceReference1.UploadInfoImgRequestBody();
            inValue.Body.id = id;
            inValue.Body.bytes = bytes;
            return ((NewUmass.ServiceReference1.ApiSoap)(this)).UploadInfoImgAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NewUmass.ServiceReference1.GetCompanyIdResponse NewUmass.ServiceReference1.ApiSoap.GetCompanyId(NewUmass.ServiceReference1.GetCompanyIdRequest request) {
            return base.Channel.GetCompanyId(request);
        }
        
        public int GetCompanyId(string domain) {
            NewUmass.ServiceReference1.GetCompanyIdRequest inValue = new NewUmass.ServiceReference1.GetCompanyIdRequest();
            inValue.Body = new NewUmass.ServiceReference1.GetCompanyIdRequestBody();
            inValue.Body.domain = domain;
            NewUmass.ServiceReference1.GetCompanyIdResponse retVal = ((NewUmass.ServiceReference1.ApiSoap)(this)).GetCompanyId(inValue);
            return retVal.Body.GetCompanyIdResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NewUmass.ServiceReference1.GetCompanyIdResponse> NewUmass.ServiceReference1.ApiSoap.GetCompanyIdAsync(NewUmass.ServiceReference1.GetCompanyIdRequest request) {
            return base.Channel.GetCompanyIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<NewUmass.ServiceReference1.GetCompanyIdResponse> GetCompanyIdAsync(string domain) {
            NewUmass.ServiceReference1.GetCompanyIdRequest inValue = new NewUmass.ServiceReference1.GetCompanyIdRequest();
            inValue.Body = new NewUmass.ServiceReference1.GetCompanyIdRequestBody();
            inValue.Body.domain = domain;
            return ((NewUmass.ServiceReference1.ApiSoap)(this)).GetCompanyIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NewUmass.ServiceReference1.UpdateKeywordRankingResponse NewUmass.ServiceReference1.ApiSoap.UpdateKeywordRanking(NewUmass.ServiceReference1.UpdateKeywordRankingRequest request) {
            return base.Channel.UpdateKeywordRanking(request);
        }
        
        public bool UpdateKeywordRanking(int companyId, int typeId, string json) {
            NewUmass.ServiceReference1.UpdateKeywordRankingRequest inValue = new NewUmass.ServiceReference1.UpdateKeywordRankingRequest();
            inValue.Body = new NewUmass.ServiceReference1.UpdateKeywordRankingRequestBody();
            inValue.Body.companyId = companyId;
            inValue.Body.typeId = typeId;
            inValue.Body.json = json;
            NewUmass.ServiceReference1.UpdateKeywordRankingResponse retVal = ((NewUmass.ServiceReference1.ApiSoap)(this)).UpdateKeywordRanking(inValue);
            return retVal.Body.UpdateKeywordRankingResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NewUmass.ServiceReference1.UpdateKeywordRankingResponse> NewUmass.ServiceReference1.ApiSoap.UpdateKeywordRankingAsync(NewUmass.ServiceReference1.UpdateKeywordRankingRequest request) {
            return base.Channel.UpdateKeywordRankingAsync(request);
        }
        
        public System.Threading.Tasks.Task<NewUmass.ServiceReference1.UpdateKeywordRankingResponse> UpdateKeywordRankingAsync(int companyId, int typeId, string json) {
            NewUmass.ServiceReference1.UpdateKeywordRankingRequest inValue = new NewUmass.ServiceReference1.UpdateKeywordRankingRequest();
            inValue.Body = new NewUmass.ServiceReference1.UpdateKeywordRankingRequestBody();
            inValue.Body.companyId = companyId;
            inValue.Body.typeId = typeId;
            inValue.Body.json = json;
            return ((NewUmass.ServiceReference1.ApiSoap)(this)).UpdateKeywordRankingAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NewUmass.ServiceReference1.GetLoginUrlResponse NewUmass.ServiceReference1.ApiSoap.GetLoginUrl(NewUmass.ServiceReference1.GetLoginUrlRequest request) {
            return base.Channel.GetLoginUrl(request);
        }
        
        public string GetLoginUrl(int companyId, int b2bId) {
            NewUmass.ServiceReference1.GetLoginUrlRequest inValue = new NewUmass.ServiceReference1.GetLoginUrlRequest();
            inValue.Body = new NewUmass.ServiceReference1.GetLoginUrlRequestBody();
            inValue.Body.companyId = companyId;
            inValue.Body.b2bId = b2bId;
            NewUmass.ServiceReference1.GetLoginUrlResponse retVal = ((NewUmass.ServiceReference1.ApiSoap)(this)).GetLoginUrl(inValue);
            return retVal.Body.GetLoginUrlResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NewUmass.ServiceReference1.GetLoginUrlResponse> NewUmass.ServiceReference1.ApiSoap.GetLoginUrlAsync(NewUmass.ServiceReference1.GetLoginUrlRequest request) {
            return base.Channel.GetLoginUrlAsync(request);
        }
        
        public System.Threading.Tasks.Task<NewUmass.ServiceReference1.GetLoginUrlResponse> GetLoginUrlAsync(int companyId, int b2bId) {
            NewUmass.ServiceReference1.GetLoginUrlRequest inValue = new NewUmass.ServiceReference1.GetLoginUrlRequest();
            inValue.Body = new NewUmass.ServiceReference1.GetLoginUrlRequestBody();
            inValue.Body.companyId = companyId;
            inValue.Body.b2bId = b2bId;
            return ((NewUmass.ServiceReference1.ApiSoap)(this)).GetLoginUrlAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NewUmass.ServiceReference1.PushInfoResponse NewUmass.ServiceReference1.ApiSoap.PushInfo(NewUmass.ServiceReference1.PushInfoRequest request) {
            return base.Channel.PushInfo(request);
        }
        
        public string PushInfo(int infoId, int b2bId) {
            NewUmass.ServiceReference1.PushInfoRequest inValue = new NewUmass.ServiceReference1.PushInfoRequest();
            inValue.Body = new NewUmass.ServiceReference1.PushInfoRequestBody();
            inValue.Body.infoId = infoId;
            inValue.Body.b2bId = b2bId;
            NewUmass.ServiceReference1.PushInfoResponse retVal = ((NewUmass.ServiceReference1.ApiSoap)(this)).PushInfo(inValue);
            return retVal.Body.PushInfoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NewUmass.ServiceReference1.PushInfoResponse> NewUmass.ServiceReference1.ApiSoap.PushInfoAsync(NewUmass.ServiceReference1.PushInfoRequest request) {
            return base.Channel.PushInfoAsync(request);
        }
        
        public System.Threading.Tasks.Task<NewUmass.ServiceReference1.PushInfoResponse> PushInfoAsync(int infoId, int b2bId) {
            NewUmass.ServiceReference1.PushInfoRequest inValue = new NewUmass.ServiceReference1.PushInfoRequest();
            inValue.Body = new NewUmass.ServiceReference1.PushInfoRequestBody();
            inValue.Body.infoId = infoId;
            inValue.Body.b2bId = b2bId;
            return ((NewUmass.ServiceReference1.ApiSoap)(this)).PushInfoAsync(inValue);
        }
    }
}
