//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewUmass.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Company_b2b168
    {
        public int id { get; set; }
        public int companyNo { get; set; }
        public int companyId { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public int classId { get; set; }
        public int regionId { get; set; }
        public int modelId { get; set; }
        public int peopleId { get; set; }
        public int studyNumId { get; set; }
        public int regFundsId { get; set; }
        public int salesAmountId { get; set; }
        public int exportAmountId { get; set; }
        public int propertyId { get; set; }
        public int provinceId { get; set; }
        public int cityId { get; set; }
        public int countyId { get; set; }
        public int firstIndustryId { get; set; }
        public int secondIndustryId { get; set; }
        public int thirdIndustryId { get; set; }
        public int licenseId { get; set; }
        public string companyStateDetail { get; set; }
        public string licenseStateDetail { get; set; }
        public string url { get; set; }
    }
}
