//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewUmass.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Company
    {
        public int id { get; set; }
        public int userId { get; set; }
        public string companyName { get; set; }
        public string shortName { get; set; }
        public string domain { get; set; }
        public string companyAddress { get; set; }
        public string mainProducts { get; set; }
        public string mainBrands { get; set; }
        public string keywords { get; set; }
        public string companyDesc { get; set; }
        public string companyPhone { get; set; }
        public string companyEmail { get; set; }
        public string companyFax { get; set; }
        public int stateId { get; set; }
        public string realName { get; set; }
        public string sex { get; set; }
        public string post { get; set; }
        public string mobile { get; set; }
        public string phone { get; set; }
        public string qq { get; set; }
        public string email { get; set; }
        public string address { get; set; }
        public string zip { get; set; }
        public string licenseCode { get; set; }
        public string companyType { get; set; }
        public string legalEntity { get; set; }
        public string regCapital { get; set; }
        public string regDate { get; set; }
        public string validDate { get; set; }
        public string businessScope { get; set; }
        public string regAuthority { get; set; }
        public string licensePath { get; set; }
    }
}
