//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewUmass.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Company_51sole
    {
        public int id { get; set; }
        public int companyId { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public string companyType { get; set; }
        public string workingModel { get; set; }
        public int bigIndustryId { get; set; }
        public int midIndustryId { get; set; }
        public int smallIndustryId { get; set; }
        public int provinceId { get; set; }
        public int cityId { get; set; }
        public int countyId { get; set; }
        public string url { get; set; }
    }
}
