//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewUmass.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Company_gtobal
    {
        public int id { get; set; }
        public int companyNo { get; set; }
        public int companyId { get; set; }
        public int userId { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public string corporation { get; set; }
        public int modeId { get; set; }
        public int industryId { get; set; }
        public string industryIdPlace { get; set; }
        public int areaId { get; set; }
        public int firstIndustryId { get; set; }
        public int secondIndustryId { get; set; }
        public int thirdIndustryId { get; set; }
        public int fourthIndustryId { get; set; }
        public int provinceId { get; set; }
        public int cityId { get; set; }
        public string url { get; set; }
        public int fifthIndustryId { get; set; }
    }
}
