//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewUmass.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Info
    {
        public int id { get; set; }
        public int companyId { get; set; }
        public int typeId { get; set; }
        public string title { get; set; }
        public string html { get; set; }
        public string imgPath { get; set; }
        public int stateId { get; set; }
        public int createTime { get; set; }
        public Nullable<int> materialId { get; set; }
    }
}
