//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewUmass.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class longtail
    {
        public int id { get; set; }
        public Nullable<int> companyid { get; set; }
        public string name { get; set; }
        public Nullable<int> engineid { get; set; }
        public string paiming { get; set; }
        public Nullable<int> websiteid { get; set; }
        public string returnurl { get; set; }
        public string updatetime { get; set; }
        public string qushi { get; set; }
        public string liuliang { get; set; }
    }
}
