//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewUmass.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Material
    {
        public int id { get; set; }
        public Nullable<int> companyId { get; set; }
        public string title { get; set; }
        public Nullable<int> C__creattime { get; set; }
        public string creatname { get; set; }
        public Nullable<int> IsDelete { get; set; }
        public Nullable<int> DeleteTime { get; set; }
        public string DeletePerson { get; set; }
    }
}
