//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewUmass.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class UdowsYunPublicEntities : DbContext
    {
        public UdowsYunPublicEntities()
            : base("name=UdowsYunPublicEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Area_51sole> Area_51sole { get; set; }
        public virtual DbSet<Area_99inf> Area_99inf { get; set; }
        public virtual DbSet<Area_atobo> Area_atobo { get; set; }
        public virtual DbSet<Area_b2b168> Area_b2b168 { get; set; }
        public virtual DbSet<Area_gtobal> Area_gtobal { get; set; }
        public virtual DbSet<Area_jqw> Area_jqw { get; set; }
        public virtual DbSet<B2B> B2B { get; set; }
        public virtual DbSet<Company> Company { get; set; }
        public virtual DbSet<Company_51sole> Company_51sole { get; set; }
        public virtual DbSet<Company_99inf> Company_99inf { get; set; }
        public virtual DbSet<Company_atobo> Company_atobo { get; set; }
        public virtual DbSet<Company_b2b168> Company_b2b168 { get; set; }
        public virtual DbSet<Company_gtobal> Company_gtobal { get; set; }
        public virtual DbSet<Company_jqw> Company_jqw { get; set; }
        public virtual DbSet<CompanyState> CompanyState { get; set; }
        public virtual DbSet<Engines> Engines { get; set; }
        public virtual DbSet<Industry_51sole> Industry_51sole { get; set; }
        public virtual DbSet<Industry_99inf> Industry_99inf { get; set; }
        public virtual DbSet<Industry_atobo> Industry_atobo { get; set; }
        public virtual DbSet<Industry_b2b168> Industry_b2b168 { get; set; }
        public virtual DbSet<Industry_gtobal> Industry_gtobal { get; set; }
        public virtual DbSet<Industry_jqw> Industry_jqw { get; set; }
        public virtual DbSet<Info> Info { get; set; }
        public virtual DbSet<InfoState> InfoState { get; set; }
        public virtual DbSet<InfoType> InfoType { get; set; }
        public virtual DbSet<KeywordRanking> KeywordRanking { get; set; }
        public virtual DbSet<KeywordType> KeywordType { get; set; }
        public virtual DbSet<Material> Material { get; set; }
        public virtual DbSet<MaterialInfo> MaterialInfo { get; set; }
        public virtual DbSet<SuccessInfo> SuccessInfo { get; set; }
        public virtual DbSet<User> User { get; set; }
        public virtual DbSet<UserControl> UserControl { get; set; }
        public virtual DbSet<UserRole> UserRole { get; set; }
        public virtual DbSet<PushInfoLog> PushInfoLog { get; set; }
        public virtual DbSet<PublishRule> PublishRule { get; set; }
    
        public virtual ObjectResult<Proc_GetAtoboIndustry_Result> Proc_GetAtoboIndustry(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Proc_GetAtoboIndustry_Result>("Proc_GetAtoboIndustry", idParameter);
        }
    }
}
